import {
  adalineImage,
  airaImage,
  // airaImg,
  // araImg,
  fayeImage,
  jayveeImage,
  // franzImg,
  // jaysonImg,
  // jayveeImg,
  jessicaImage,
  // jhonasImg,
  paulImage,
  rubeanImage,
  samImage,
  // kaiImg,
  // kennethImg,
  // marviuzImg,
  // neilImg,
  // samImg,
  // thirdImage,
  // sirThirdImg,
  // sirThirdImage,
  jhonasImage,
} from '@/assets/images';

export const OUR_TEAM = [
  {
    id: 1,
    name: 'Paul',
    position: 'Chief Executive Officer (CEO)',
    img: paulImage,
  },
  // {
  //   id: 2,
  //   name: 'Third',
  //   position: 'Chief Operations Officer (COO)',
  //   img: sirThirdImage,
  // },
  {
    id: 3,
    name: 'Faye',
    position: 'Corporate Secretary',
    img: fayeImage,
  },
  {
    id: 4,
    name: 'Jayvee',
    position: 'Operations Manager',
    img: jayveeImage,
  },
  {
    id: 5,
    name: 'Sam',
    position: 'Web Developer',
    img: samImage,
  },
  {
    id: 6,
    name: 'John Aira',
    position: 'Web Developer',
    img: airaImage,
  },
  {
    id: 7,
    name: 'Rubean',
    position: 'Web Developer',
    img: rubeanImage,
  },
  {
    id: 8,
    name: 'Adaline',
    position: 'Web Developer / Marketing Officer',
    img: adalineImage,
  },
  {
    id: 9,
    name: 'Jessica',
    position: 'Admin/HR/Accounting',
    img: jessicaImage,
  },

  // {
  //   id: 9,
  //   name: 'Toni Padua',
  //   position: 'Head UI/UX',
  //   img: toniImg,
  // },
  // {
  //   id: 10,
  //   name: 'Kenneth Gunabe',
  //   position: 'Sr. Front-end Developer',
  //   img: kennethImg,
  // },
  // {
  //   id: 11,
  //   name: 'Neil Monzales',
  //   position: 'Sr. Fullstack Developer/DevOps',
  //   img: neilImg,
  // },
  // {
  //   id: 12,
  //   name: 'Jayson Timkang',
  //   position: 'Sales Executive',
  //   img: jaysonImg,
  // },
  {
    id: 10,
    name: 'Jhonas',
    position: 'Web Developer',
    img: jhonasImage,
  },
] as const;
