import {
  kaiImg,
  araImg,
  jayveeImg,
  airaImg,
  marcusImg,
  franzImg,
  samImg,
  sirThirdImg,
  kennethImg,
  neilImg,
  toniImg,
  jaysonImg,
  jhonasImg,
} from '@/assets/images';

export const OUR_TEAM = [
  {
    id: 1,
    name: 'Florante Sugian III',
    position: 'Owner/CTO',
    img: sirThirdImg,
  },
  {
    id: 2,
    name: 'Marcus Leviticus Dela Cruz',
    position: 'Front-end Developer',
    img: marcusImg,
  },
  {
    id: 3,
    name: 'Francis "Franz" Bernardino',
    position: 'Front-end Developer',
    img: franzImg,
  },
  {
    id: 4,
    name: 'Sammuel "Sam" Espiritu',
    position: 'Front-end Developer',
    img: samImg,
  },
  {
    id: 5,
    name: 'Frances Kaye "Kai" Albis',
    position: 'Admin Officer',
    img: kaiImg,
  },
  {
    id: 6,
    name: 'Jayvee Ramos',
    position: 'IT Engineering Manager',
    img: jayveeImg,
  },
  {
    id: 7,
    name: 'John Aira Feleo',
    position: 'Back-end Developer',
    img: airaImg,
  },
  {
    id: 8,
    name: 'Ara Belle Agarem',
    position: 'Marketing and SEO Specialist',
    img: araImg,
  },
  {
    id: 8,
    name: 'Toni Padua',
    position: 'Head UI/UX',
    img: toniImg,
  },
  {
    id: 9,
    name: 'Kenneth Gunabe',
    position: 'Sr. Front-end Developer',
    img: kennethImg,
  },
  {
    id: 10,
    name: 'Neil Monzales',
    position: 'Sr. Fullstack Developer/DevOps',
    img: neilImg,
  },
  {
    id: 11,
    name: 'Jayson Timkang',
    position: 'Sales Executive',
    img: jaysonImg,
  },
  {
    id: 12,
    name: 'Jhonas Lalo',
    position: 'Back-end Developer',
    img: jhonasImg,
  },
] as const;
