import { type StaticImageData } from 'next/image';
import {
  websiteTemplate1,
  websiteTemplate2,
  websiteTemplate3,
  websiteTemplate4,
  websiteTemplate5,
  websiteTemplate6,
  websiteTemplate7,
  websiteTemplate8,
  websiteTemplate9,
  websiteTemplate10,
  websiteTemplate11,
  websiteTemplate12,
  websiteTemplate13,
  websiteTemplate14,
  websiteTemplate15,
  websiteTemplate16,
  websiteTemplate17,
  websiteTemplate18,
  websiteTemplate19,
  websiteTemplate20,
  websiteTemplate21,
  websiteTemplate22,
  websiteTemplate23,
  websiteTemplate24,
  websiteTemplate1M,
  websiteTemplate2M,
  websiteTemplate3M,
  websiteTemplate4M,
  websiteTemplate5M,
  websiteTemplate6M,
  websiteTemplate7M,
  websiteTemplate8M,
  websiteTemplate9M,
  websiteTemplate10M,
  websiteTemplate11M,
  websiteTemplate12M,
  websiteTemplate13M,
  websiteTemplate14M,
  websiteTemplate15M,
  websiteTemplate16M,
  websiteTemplate17M,
  websiteTemplate18M,
  websiteTemplate19M,
  websiteTemplate20M,
  websiteTemplate21M,
  websiteTemplate22M,
  websiteTemplate23M,
  websiteTemplate24M,
} from '@/assets/images';

export enum TemplateFeatures {
  Home = 'Home',
  About = 'About',
  Services = 'Services',
  Contact = 'Contacts',
  Features = 'Features',
  Blog = 'Blog',
  Team = 'Team',
  Faq = 'FAQ',
  Clients = 'Clients',
}

export interface ProductsTemplates {
  title: string;
  image: StaticImageData;
  imageMobile: StaticImageData;
  id: number;
  features: TemplateFeatures[];
  imgsrc?: string;
}

export const WEBTEMPLATES: ProductsTemplates[] = [
  {
    id: 1,
    title: 'web-template-1',
    image: websiteTemplate1,
    imageMobile: websiteTemplate1M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-1.png',
  },
  {
    id: 2,
    title: 'web-template-2',
    image: websiteTemplate2,
    imageMobile: websiteTemplate2M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Blog,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-2.png',
  },
  {
    id: 3,
    title: 'web-template-3',
    image: websiteTemplate3,
    imageMobile: websiteTemplate3M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-3.png',
  },
  {
    id: 4,
    title: 'web-template-4',
    image: websiteTemplate4,
    imageMobile: websiteTemplate4M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-4.png',
  },
  {
    id: 5,
    title: 'web-template-5',
    image: websiteTemplate5,
    imageMobile: websiteTemplate5M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Features,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-5.png',
  },
  {
    id: 6,
    title: 'web-template-6',
    image: websiteTemplate6,
    imageMobile: websiteTemplate6M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-6.png',
  },
  {
    id: 7,
    title: 'web-template-7',
    image: websiteTemplate7,
    imageMobile: websiteTemplate7M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Features,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-7.png',
  },
  {
    id: 8,
    title: 'web-template-8',
    image: websiteTemplate8,
    imageMobile: websiteTemplate8M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Blog,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-8.png',
  },
  {
    id: 9,
    title: 'web-template-9',
    image: websiteTemplate9,
    imageMobile: websiteTemplate9M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-9.png',
  },
  {
    id: 10,
    title: 'web-template-10',
    image: websiteTemplate10,
    imageMobile: websiteTemplate10M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-10.png',
  },
  {
    id: 11,
    title: 'web-template-11',
    image: websiteTemplate11,
    imageMobile: websiteTemplate11M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Blog,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-11.png',
  },
  {
    id: 12,
    title: 'web-template-12',
    image: websiteTemplate12,
    imageMobile: websiteTemplate12M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-12.png',
  },
  {
    id: 13,
    title: 'web-template-13',
    image: websiteTemplate13,
    imageMobile: websiteTemplate13M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Features,
      TemplateFeatures.Clients,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-13.png',
  },
  {
    id: 14,
    title: 'web-template-14',
    image: websiteTemplate14,
    imageMobile: websiteTemplate14M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Features,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-14.png',
  },
  {
    id: 15,
    title: 'web-template-15',
    image: websiteTemplate15,
    imageMobile: websiteTemplate15M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-15.png',
  },
  {
    id: 16,
    title: 'web-template-16',
    image: websiteTemplate16,
    imageMobile: websiteTemplate16M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-16.png',
  },
  {
    id: 17,
    title: 'web-template-17',
    image: websiteTemplate17,
    imageMobile: websiteTemplate17M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Features,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-17.png',
  },
  {
    id: 18,
    title: 'web-template-18',
    image: websiteTemplate18,
    imageMobile: websiteTemplate18M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-18.png',
  },
  {
    id: 19,
    title: 'web-template-19',
    image: websiteTemplate19,
    imageMobile: websiteTemplate19M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Features,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-19.png',
  },
  {
    id: 20,
    title: 'web-template-20',
    image: websiteTemplate20,
    imageMobile: websiteTemplate20M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-20.png',
  },
  {
    id: 21,
    title: 'web-template-21',
    image: websiteTemplate21,
    imageMobile: websiteTemplate21M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-21.png',
  },
  {
    id: 22,
    title: 'web-template-22',
    image: websiteTemplate22,
    imageMobile: websiteTemplate22M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-22.png',
  },
  {
    id: 23,
    title: 'web-template-23',
    image: websiteTemplate23,
    imageMobile: websiteTemplate23M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-23.png',
  },
  {
    id: 24,
    title: 'web-template-24',
    image: websiteTemplate24,
    imageMobile: websiteTemplate24M,
    features: [
      TemplateFeatures.Home,
      TemplateFeatures.About,
      TemplateFeatures.Services,
      TemplateFeatures.Contact,
      TemplateFeatures.Blog,
    ],
    imgsrc: 'src/assets/images/web-templates/web-template-24.png',
  },
];
