import {
  teamImg1,
  teamImg2,
  teamImg3,
  teamImg4,
  teamImg5,
  teamImg6,
  teamImg7,
  teamImg8,
  franzProfile,
  marcusProfile,
  samProfile,
  jayveeProfile,
  thirdProfile,
  kaiProfile,
  airaProfile,
  araProfile,
  kaiteam,
  jayveeteam,
  arateam,
  airateam,
  samteam,
  marcusteam,
  franzteam,
} from '@/assets/images';

export const TEAM = [
  {
    id: 1,
    name: 'Florante Sugian III',
    position: 'Owner/CTO',
    src: teamImg1,
    profile: thirdProfile,
  },
  {
    id: 2,
    name: 'Marcus Leviticus Dela Cruz',
    position: 'Front-end Developer',
    src: teamImg2,
    profile: marcusProfile,
  },
  {
    id: 3,
    name: 'Francis "Franz" Bernardino',
    position: 'Front-end Developer',
    src: teamImg3,
    profile: franzProfile,
  },
  {
    id: 4,
    name: 'Sammuel "Sam" Espiritu',
    position: 'Front-end Developer',
    src: teamImg4,
    profile: samProfile,
  },
  {
    id: 5,
    name: 'Frances Kaye "Kai" Albis',
    position: 'Admin Officer',
    src: teamImg5,
    profile: kaiProfile,
  },
  {
    id: 6,
    name: 'Jayvee Ramos',
    position: 'IT Engineering Manager',
    src: teamImg6,
    profile: jayveeProfile,
  },
  {
    id: 7,
    name: 'John Aira Feleo',
    position: 'Back-end Developer',
    src: teamImg7,
    profile: airaProfile,
  },
  {
    id: 8,
    name: 'Ara Belle Agarem',
    position: 'Marketing and SEO Specialist',
    src: teamImg8,
    profile: araProfile,
  },
] as const;

export const TEAM1 = [
  {
    id: 1,
    name: 'Frances Kaye Albis',
    position: 'Admin Officer',
    src: kaiteam,
    profile: kaiProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
  {
    id: 2,
    name: 'Jayvee Ramos',
    position: 'IT Engineering Manager',
    src: jayveeteam,
    profile: jayveeProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
      facebook: 'https://facebook.com',
    },
  },
  {
    id: 3,
    name: 'Ara Belle Agarem',
    position: 'Marketing and SEO Specialist',
    src: arateam,
    profile: araProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
  {
    id: 4,
    name: 'John Aira Feleo',
    position: 'Back-end Developer',
    src: airateam,
    profile: airaProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
  {
    id: 5,
    name: 'Sammuel Espiritu',
    position: 'Front-end Developer',
    src: samteam,
    profile: samProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
  {
    id: 6,
    name: 'Marcus Leviticus Dela Cruz',
    position: 'Front-end Developer',
    src: marcusteam,
    profile: marcusProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
  {
    id: 7,
    name: 'Francis Bernardino',
    position: 'Front-end Developer',
    src: franzteam,
    profile: franzProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
  {
    id: 8,
    name: 'Florante Sugian III',
    position: 'Owner/CTO',
    src: thirdProfile,
    profile: thirdProfile,
    socialMedia: {
      github: 'https://github.com',
      linkedin: 'https://github.com',
    },
  },
] as const;
