// Generated by https://quicktype.io

export interface Posts {
  data: PostData;
  extensions: Extensions;
}

export interface PostData {
  posts: PostsClass;
}

export interface PostsClass {
  edges: Edge[];
}

export interface Edge {
  node: EdgeNode;
  cursor: string;
}

export interface EdgeNode {
  author: Author;
  slug: string;
  title: string;
  excerpt: string;
  featuredImage: FeaturedImage | null;
  date: string;
}

export interface Author {
  node: AuthorNode;
}

export interface AuthorNode {
  name: string;
  avatar: Avatar;
}

export interface Avatar {
  size: number;
  url: string;
}

export interface FeaturedImage {
  node: FeaturedImageNode;
}

export interface FeaturedImageNode {
  sourceUrl: string;
  mediaDetails: MediaDetails;
}

export interface MediaDetails {
  height: number;
  width: number;
}

export interface Extensions {
  debug: Debug[];
}

export interface Debug {
  type: string;
  message: string;
}
