// Generated by https://quicktype.io

export interface PostBySlug {
  data: Data;
  extensions: Extensions;
}

export interface Data {
  post: Post | null;
}

export interface Post {
  author: Author;
  slug: string;
  title: string;
  featuredImage: FeaturedImage | null;
  date: string;
  content: string;
}

export interface Author {
  node: AuthorNode;
}

export interface AuthorNode {
  name: string;
  avatar: Avatar;
}

export interface Avatar {
  size: number;
  url: string;
}

export interface FeaturedImage {
  node: FeaturedImageNode;
}

export interface FeaturedImageNode {
  sourceUrl: string;
  mediaDetails: MediaDetails;
}

export interface MediaDetails {
  height: number;
  width: number;
}

export interface Extensions {
  debug: Debug[];
}

export interface Debug {
  type: string;
  message: string;
}
